Feature/c menu
GothicKit/phoenix-csharp-interface pull request #31
Opened 2023-08-10 07:06 UTC by JucanAndreiDaniel

Add c_menu and c_menu_item data format and data

2023-08-10 19:23 UTC, JaXt0r requested changes
Test failed unfortunately:
![image](https://github.com/GothicKit/phoenix-csharp-interface/assets/120568393/f3944614-80b3-42f8-abc6-6367323fd4e3)

2023-08-10 19:36 UTC, JucanAndreiDaniel commented
> Test failed unfortunately: ![image](https://user-images.githubusercontent.com/120568393/259852460-f3944614-80b3-42f8-abc6-6367323fd4e3.png)

It's weird, for me it doesn't give issues

2023-08-10 19:58 UTC, JaXt0r commented
> > Test failed unfortunately: ![image](https://user-images.githubusercontent.com/120568393/259852460-f3944614-80b3-42f8-abc6-6367323fd4e3.png)
> 
> It's weird, for me it doesn't give issues

Can you please check with German game language? It seems to be a language agnostic check which shouldn't be.

2023-08-10 20:35 UTC, JucanAndreiDaniel commented
> > > Test failed unfortunately: ![image](https://user-images.githubusercontent.com/120568393/259852460-f3944614-80b3-42f8-abc6-6367323fd4e3.png)
> > 
> > 
> > It's weird, for me it doesn't give issues
> 
> Can you please check with German game language? It seems to be a language agnostic check which shouldn't be.

![image](https://github.com/GothicKit/phoenix-csharp-interface/assets/23665744/c34cfafc-e1b5-493c-8e25-77953ac14bc8)
This is with the german version

2023-08-11 05:07 UTC, JaXt0r commented
> > > > Test failed unfortunately: ![image](https://user-images.githubusercontent.com/120568393/259852460-f3944614-80b3-42f8-abc6-6367323fd4e3.png)
> > > 
> > > 
> > > It's weird, for me it doesn't give issues
> > 
> > 
> > Can you please check with German game language? It seems to be a language agnostic check which shouldn't be.
> 
> ![image](https://user-images.githubusercontent.com/23665744/259868311-c34cfafc-e1b5-493c-8e25-77953ac14bc8.png) This is with the german version

Exactly. So the demand for a test is, that it is language independent if possible. (Sure Russian fails as well, but we should have green tests for German and English at least as these are the languages we develop with).

2023-08-12 20:39 UTC, JucanAndreiDaniel commented
> > > > > Test failed unfortunately: ![image](https://user-images.githubusercontent.com/120568393/259852460-f3944614-80b3-42f8-abc6-6367323fd4e3.png)
> > > > 
> > > > 
> > > > It's weird, for me it doesn't give issues
> > > 
> > > 
> > > Can you please check with German game language? It seems to be a language agnostic check which shouldn't be.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/23665744/259868311-c34cfafc-e1b5-493c-8e25-77953ac14bc8.png) This is with the german version
> 
> Exactly. So the demand for a test is, that it is language independent if possible. (Sure Russian fails as well, but we should have green tests for German and English at least as these are the languages we develop with).

Agree with you, should we merge this PR and have another PR to solve these issues?

2023-08-12 21:25 UTC, JaXt0r commented
It was just one test from your new main menu feature. Please fix it with this PR. Others are working already fine for ger and eng which is sufficient imho.

2023-08-21 14:51 UTC, JucanAndreiDaniel commented
> It was just one test from your new main menu feature. Please fix it with this PR. Others are working already fine for ger and eng which is sufficient imho.

Ok, now i know what the issue was, i forgot to push to phoenix-shared the c-menu stuff :D
can be merged after https://github.com/GothicKit/phoenix-shared-interface/pull/38

2023-08-28 19:49 UTC, JaXt0r approved these changes
Please change your formatter to "do not be greedy". Example below.
Other than that: Test is working and feature looks good. :-)

2023-08-28 19:49 UTC, JaXt0r commented on PxCs/Interface/PxVm.cs
> +
Please stop your formatter from reformatting all the lines. ;-)

e.g. these lines were intentionally intended this way.

2023-08-30 16:59 UTC, merged